Add HTML attribute to record iframe usage
Frogtek/frogtek.github.io pull request #31
Opened 2019-12-05 08:59 UTC by oscarsa

2019-12-05 09:00 UTC, cati-risquez approved these changes

2019-12-05 09:02 UTC, RicardoBuera approved these changes

2019-12-10 09:07 UTC, durey approved these changes

2019-12-10 09:56 UTC, durey requested changes
Deberías fusionar todos los commits, y llamar la PR y el commit final algo como "Remove HotJar library"

2019-12-10 11:18 UTC, durey approved these changes
¿Por qué no fusionas los dos commits que quedan? Uno añade una cosa que el siguiente elimina.

2019-12-10 11:38 UTC, merged