Add legal.html and include in legal.md file (for ttk without header a…
Frogtek/frogtek.github.io pull request #40
Opened 2020-03-19 18:03 UTC by cati-risquez

…nd footer)

2020-03-19 18:09 UTC, durey approved these changes
Jodo, esto es matar moscas a cañonazos... La gracia de usar Jekyll es escribir solo en Markdown. Si necesitas diferencias en el HTML que genera, se define una nueva plantilla, no se convierte todo el Markdown a HTML... Lo dejamos así, por no bloquearlo, y otro día lo hacemos bien en pareja si quieres.

2020-03-19 18:12 UTC, durey commented
Intenta también que los títulos de commits y PR no se trunquen por ser largos, y recuerda no explicar detalles técnicos, sino lo que se quiere conseguir. No sé si algo como "Migrate legal text from Markdown to HTML (to avoid problems in TT)".

- "ttk" no lo ha usado casi nadie en la historia de Frogtek :trollface:
- Da igual el nombre específico de ficheros o clases en títulos de PR/commits

2020-03-19 18:23 UTC, cati-risquez commented
@durey  Gracias por la review! no es urgente, así que se puede quedar bloqueado, cuando quieras lo vemos en pair si tienes unos minutos solo con explicarmelo, la idea es tener solo el texto, sin encabezado ni pie de página. Yo eso de matar moscas a cañonazos, para mi que haya funcionado ha sido un reto, es mi primer contacto en solitario con html, y lo último y primero que hice, fue en ticketbox, hace como dos años ya. Es la única solución que he encontrado. Si no tienes tiempo, hazme una propuesta de mejora de cómo se tiene que hacer y ya me las apaño para arreglarlo.

2020-03-23 02:34 UTC, durey requested changes
@cati-risquez Sin problema, y tienes razón, felicidades por habértelas apañado, que eso siempre es lo más importante, jejeje. Mañana lo arreglamos en 5 minutos, ya verás qué fácil. 

El problema principal (además de perder el Markdown) es que el HTML final generado en cada página debe ser sintácticamente correcto, y ahora no lo está en ninguna de las dos páginas (la de `legal.html` tiene dos tags `<html>` anidados, y la de `policy.html` tiene un `<html>` que es hijo de `<br>`, ¡dos pecados! :wink: ). Que te funcione en el Chrome es solo gracias a que él se las apaña bien para interpretar lo que debería haberse hecho, pero nadie te lo asegura en el futuro, ni en otros navegadores.

2020-03-23 11:21 UTC, closed without merging